### ISSUE TITLE
ERROR by vim.o.t_Co = "256" 

### ISSUE THREAD

**Issue by ghost** [Iron-E/nvim-soluarized#1]
Hello!

I get this error after updating nvim-nightly. -> https://www.reddit.com/r/neovim/comments/nt0li1/weird_error_after_updating/

I think the problem is [here](https://github.com/Iron-E/nvim-soluarized/blob/master/lua/soluarized.lua#L30)

**Comment by Iron-E** [comment]
Thanks for using this plugin!

[I fixed this bug upstream](https://github.com/Iron-E/nvim-highlite/commit/9c15a789df5af1d3c83c0d680154ca226253eb26) but forgot to merge it into this repository. I'll merge later today and from there it should be all set

**Comment by Iron-E** [comment]
Should be fixed. Can you update and let me know?

**Comment by ghost** [comment]
FIXED!. It is working perfectly. Many thanks!
