### ISSUE TITLE
Cursor line with dark background

### ISSUE THREAD

**Issue by tissieres** [Iron-E/nvim-soluarized#2]
Hello, 
Very recently I got an issue with your theme. The cursor line in insert mode has a very dark background as shown on the picture below.

![screenshot-20220719-101530](https://user-images.githubusercontent.com/2410978/179702162-a9370dc1-3f62-4f97-afe8-ba1c1ce18765.png)

I searched for a while the cause of this change but did not find anything. It could be related to an update of nvim-treesitter maybe?

**Comment by Iron-E** [comment]
Thanks for the report. I'll look into it

**Comment by Iron-E** [comment]
Can you check out the attached PR? 

Edit: in case you aren't already, you will need Neovim 0.7+

**Comment by tissieres** [comment]
Thanks for fixing so quickly. I tested the PR and it fixed the problem on my side.

**Comment by Iron-E** [comment]
Happy to help :)
